task/config/routes.rb
Task::Application.routes.draw do
  resources :images

  devise_for :users

  resources :users

   root :to => 'images#index'

end

task/app/models/image.rb
class Image < ActiveRecord::Base
    attr_accessible :description, :image, :user_id
    default_scope order("images.created_at DESC")

    belongs_to :user
    mount_uploader :image, ImageUploader
end

task/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

task/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

task/app/controllers/images_controller.rb
class ImagesController < ApplicationController
    require 'bunny'
    require 'json'

    before_filter :authenticate_user!, :only => [:new, :create]

######################################
    #Bunny Stuff
######################################
    def self.client
        unless @client
            c = Bunny.new
            c.start
            @client = c
        end
        @client
    end

    def self.send_image
      @send_image ||= client.exchange('', :durable => true)
    end
######################################

    def index
        @images = Image.all
    end

    def show
        @image = Image.find(params[:id])
    end

    def new
        @image = Image.new
    end

    def create
        @image = Image.new(params[:image])
        @image.user_id = current_user.id
        if @image.save
            path = @image.image.url.split("/").slice(0..-2).join("/") + "/"
            file = @image.image.url.split("/").last
       
            str = {:image_id => @image.id ,:root_path => Rails.root, :image_path => path, :image_file => file}
            ImagesController.send_image.publish str.to_json , :key => "images"
            redirect_to root_url, :notice => "Image uploaded!"
        else
            render :new
        end
    end
end

task/app/controllers/users_controller.rb
class UsersController < ApplicationController
end

task/app/helpers/application_helper.rb
module ApplicationHelper
end

task/app/helpers/images_helper.rb
module ImagesHelper
end

task/app/helpers/users_helper.rb
module UsersHelper
end

task/app/views/images/index.html.erb
<% if signed_in? %>
    <p><%= link_to "uploade image", new_image_path %></p>
<% end %>
<h1>Image Overview</h1>

<div id="images">
    <% @images.each do |image| %>
        <div>
            <p><%= image_tag image.thumb_url %></p>
            <p><%= image.description %></p>
        </div>
    <% end %>
</div>

task/app/views/images/new.html.erb
<div class="image-form">
  <%= form_for @image, :html => {:multipart => true} do |f| %>
    <% if @image.errors.any? %>
      <div class="error_messages signing-error">
        <ul>
          <% for message in @image.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </p>
  
    <p>
      <%= f.label :image %>
      <%= f.file_field :image, :class => "textbox-a", :placeholder => "Image File" %>
    </p>
    <p>
      <%= f.submit "Upload Image", :class => "btn-a" %>
    </p>
  <% end %>
</div>

task/app/views/images/show.html.erb
<h1>Image Detailed</h1>

<div>
    <p><%= image_tag @image.image_url %></p>
    <p><%= @image.description %></p>
</div>

task/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Task" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Task</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "images", images_path  %></li>
              <li><%= link_to "login",  new_user_session_path %></li>
              <li><%= link_to "register", new_user_registration_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="http://localhost:3001/socket.io/socket.io.js"></script>
    <%= javascript_include_tag "application" %>
  </body>
</html>